version: '3'

services:
  db:
    build:
      context: ./docker/db
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
  redis:
    build:
      context: ./docker/redis
  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        - XDEBUG_REMOTE_ENABLE=${XDEBUG_REMOTE_ENABLE}
        - XDEBUG_REMOTE_AUTOSTART=${XDEBUG_REMOTE_AUTOSTART}
        - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
        - XDEBUG_REMOTE_PORT=${XDEBUG_REMOTE_PORT}
        - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
        - XDEBUG_REMOTE_CONNECT_BACK=${XDEBUG_REMOTE_CONNECT_BACK}
    volumes:
      - ./src:/var/www/tv
    ports:
      - ${PHP_FPM_PORT}:${PHP_FPM_PORT}
    user: "$UID"
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./src:/var/www/tv
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    depends_on:
      - php-fpm

volumes:
  db:
